### ISSUE TITLE
Add support for default resolver

### ISSUE THREAD

**Issue by varholak-peter** [claus/storyblok-rich-text-react-renderer#1]
Right now, if there is no resolver mapped to a required node or blok type, the renderer returns `null`.

It would be nice to allow `defaultRenderer` in options. This way we can provide our own placeholder component instead of the rendering silently failing.
Additional thing to consider is adding a console warning when no resolver for given node is found. This can further help with diagnostic of not yet implemented components or typos.

**Comment by claus** [comment]
https://github.com/claus/storyblok-rich-text-react-renderer#default-blok-resolver
