### ISSUE TITLE
Rich text renderer not working with NextJS

### ISSUE THREAD

**Issue by janoschsworkspace** [claus/storyblok-rich-text-react-renderer#15]
I've tried to use the library in my NextJS app, but haven't gotten it to work. 
Here's the function I created to render the content: 
`const RichText = (document) => {
  return <div>{render(document)}</div>;
};`

And here's how that function is called in my JSX:
` <RichText document={story.content.Content.content[1]} />`

`story.content.Content.content[1]` is in this case equal to `{
  type: 'paragraph',
  content: [ { text: "some text", type: 'some text' } ]
}`

This renders nothing to the screen. Am I missing something here?

**Comment by claus** [comment]
The render function expects the root of the rich text object: `{ type: "doc", content: [ ... ] }`, so in your case that probably is `story.content.Content`.

**Comment by janoschsworkspace** [comment]
In my case, `story.content.Content` is an array of lots of objects that look like this `{ type: "doc", content: [ ... ] }`. I tried rendering just the first element of the array with `story.content.Content.content[1]` and I also tried mapping the entire array, but neither worked.

**Comment by janoschsworkspace** [comment]
But either way, `story.content.Content.content[1]` does have the shape you mentioned above and in the documentation (`{ type: "doc", content: [ ... ] }`)

**Comment by claus** [comment]
Ok weird. Can you log `JSON.stringify(story.content.Content.content[1], undefined, 2)` and paste it here?

**Comment by janoschsworkspace** [comment]
Oh yes, just made it work. You were right, I don't know why it didn't work when I tried it before...

Thank you for your help :)
