### ISSUE TITLE
Rehydration Error for NODE_IMAGE resolver

### ISSUE THREAD

**Issue by GavOutdoors** [claus/storyblok-rich-text-react-renderer#25]
Hi, 
I'm using Next JS and decided to add an image resolver for my wrapper for the Next Image. 
However, I am getting rehydration errors even without using that component for the resolver. 
```
render(blok.content,
                    {
                            nodeResolvers: {
                                [NODE_IMAGE]: (children, props) => <p>Image Placeholder</p>
                    },
```
If I remove the NODE_IMAGE node resolver, not React rehydration error.

Any ideas?

Cheers,
Gav

**Comment by claus** [comment]
Hmm weird. Can you post the error log here?

**Comment by GavOutdoors** [comment]
I've just found the problem.

This is the image in the Storyblok Rich Text editor. 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/79079903/197726850-deb7f143-0e5b-4d4b-a1e0-dcb75c2fe617.png">

In my test for the image handler, I wrapped it in a <p>.
`[NODE_IMAGE]: (children, props) => <p>Image Placeholder</p>`

Looking at one of the errors in the log, it says this: 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/79079903/197727165-33234f2b-e25a-4c69-88ab-804703d6c859.png">

If I look at the HTML source, I can see that the Storyblok editor has placed the img inside the paragraph, and so testing with a p creates a nested p ;-) 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/79079903/197727516-04dcfb4f-7578-4d3e-a4c6-6946c58371e4.png">

Replacing p with span in my test works without the rehydration error! :-D
[NODE_IMAGE]: (children, props) => <span>Image Placeholder</span>

So, my quick little test turned into a head-scratcher!

**Comment by claus** [comment]
Ah yeah that once happened to me as well :) Glad you figured it out!

**Comment by lemsdentsu** [comment]
Having this problem as well, but not with a nested `p` element. I want to show the image in a `figure` element, so that I can add a `figcaption`, but they are always wrapped in `p` elements. I'm getting the following error:

````
Warning: validateDOMNesting(...): <figcaption> cannot appear as a descendant of <p>.
````
The issue seems to be that images are always wrapped in a paragraph, any way to circumvent this?

**Comment by GavOutdoors** [comment]
Hi Rene,

Thanks for letting me know and thanks for reaching out.
I’ll be sure to try the feature soon, but unable to do so at the moment.

Thanks,
Gav

From: René Lems ***@***.***>
Date: Wednesday, 30 November 2022 at 15:18
To: claus/storyblok-rich-text-react-renderer ***@***.***>
Cc: Gav Grayston (GOWTK) ***@***.***>, State change ***@***.***>
Subject: Re: [claus/storyblok-rich-text-react-renderer] Rehydration Error for NODE_IMAGE resolver (Issue #25)

Having this problem as well, but not with a nested p element. I want to show the image in a figure element, so that I can add a figcaption, but they are always wrapped in p elements. I'm getting the following error:

Warning: validateDOMNesting(...): <figcaption> cannot appear as a descendant of <p>.

The issue seems to be that images are always wrapped in a paragraph, any way to circumvent this?

**Comment by 12** [comment]
Has there been any developments or workarounds for this? We are also wanting to render images inside a `figure` element with a corresponding `figcaption` but as `figure` is block-level, it cannot be nested within a paragraph element.
