### ISSUE TITLE
Storyblok now supports new marks: superscript, subscript.

### ISSUE THREAD

**Issue by Gerosullivan** [claus/storyblok-rich-text-react-renderer#30]
Would it be possible to have inline support for these?

**Comment by claus** [comment]
@Gerosullivan Yes, i'll look into it

**Comment by claus** [comment]
Resolvers added in 2.7.1:

- NODE_EMOJI
- MARK_SUBSTRING
- MARK_SUPERSTRING
- MARK_HIGHLIGHT
- MARK_TEXT_STYLE

Thank you!
