### ISSUE TITLE
Support for textStyle mark resolver

### ISSUE THREAD

**Issue by Andy1Blue** [claus/storyblok-rich-text-react-renderer#31]
**Description:**

Stroyblok v2 have a possibility to change e.g. text color, please add new const to the markResolvers object.

**Example:**

```js
textStyle: (children, props) => <span style={{ ...props }}>{children}</span>
```

**Comment by jklmnopr** [comment]
Also, emojis are here in RichText. Would be great to have support for those 👍 💯

**Comment by claus** [comment]
Resolvers added in 2.7.1:

- NODE_EMOJI
- MARK_SUBSTRING
- MARK_SUPERSTRING
- MARK_HIGHLIGHT
- MARK_TEXT_STYLE

Thank you!
