### ISSUE TITLE
Detecting first child

### ISSUE THREAD

**Issue by davshoward** [claus/storyblok-rich-text-react-renderer#37]
Hey, love the plugin. 

Was wondering if there was any way of detecting whether an element is the "first" child or not?

Specifically for the use case of a heading to be able to do something like this:

```
[NODE_HEADING]: (children, props) => {
	const { level } = props;
	const isFirstChild = ???;

	return (
		<H {...level} spacing={isFirstChild ? 'b' : 'y'}>
			{children}
		</H>
	);
}
```

Cheers

**Comment by claus** [comment]
No that's not possible, unfortunately. I don't know what your spacing prop does, but maybe CSS can help? (`:first-child` or `:first-of-type`)

**Comment by davshoward** [comment]
No worries :-)
