### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by lisilinhart** [claus/storyblok-rich-text-react-renderer#4]
Hi, I was implementing a storyblok example with https://github.com/vercel/commerce trying to use this package instead of the Storyblok renderer, but then I noticed that the rendered didn't have the Typescript types defined. Would there be a possibility from your side to add them? Maybe some of the types from the Storyblok JS client can be useful: https://github.com/storyblok/storyblok-js-client/blob/master/types/index.d.ts

**Comment by dohomi** [comment]
@claus @lisilinhart I started a PR here: https://github.com/claus/storyblok-rich-text-react-renderer/pull/5

Let me know what you think about it.

**Comment by dohomi** [comment]
To try out the rewritten project here is a temporary project-name:
```
 "storyblok-rich-text-react-renderer-beta": "^3.0.0-pre3",
```
