### ISSUE TITLE
Link's custom attributes aren't included into type definitions

### ISSUE THREAD

**Issue by guilhermespopolin** [claus/storyblok-rich-text-react-renderer#41]
Hello,
First of all thanks for making this 🙌🏻 

I've noticed custom attributes for links are not included into type definitions. I've take the liberty of creating this [PR](https://github.com/claus/storyblok-rich-text-react-renderer/pull/40) that include them. It would be nice be to able to use/pass down those values while implementing a resolver for `MARK_LINK`.

Let me know if there's something missing and/or what not.

Best regards,

**Comment by claus** [comment]
Thanks so much!
Published as 2.9.0.

**Comment by guilhermespopolin** [comment]
No worries. Thanks for updating it so quickly 🙌🏻
