### ISSUE TITLE
SSR rendering

### ISSUE THREAD

**Issue by pedrosousa13** [claus/storyblok-rich-text-react-renderer#44]
Hi @claus , I was wondering if we could make this load on the server. Right now you are loading the resolvers on the client.
Do you think it would be an easy refactor?

**Comment by claus** [comment]
I'm not sure i follow. What do you mean with "loading the resolvers on the client"?

**Comment by pedrosousa13** [comment]
Please ignore this issue, the problem was on our side and not at the rich-text-renderer. Apologies.

**Comment by claus** [comment]
No worries!
