### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by alcoceba** [claus/storyblok-rich-text-react-renderer#51]
When rendering a rich text component, the following warning appears in the console:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Text`. See https://reactjs.org/link/warning-keys for more information.
    at span
    at Text (webpack-internal:///(app-pages-browser)/./src/components/landing/storyblok/Text.js:64:11)
    at StoryblokComponent (Server)
    ....
```

This warning suggests that some child elements in a list are missing a unique key property, which could potentially cause rendering issues.

### Steps to Reproduce

1. Create a field of type Rich Text in Storyblok.
2. Add plain text content
3. Import the rich text renderer library and render the content using the following code:

```
import { render } from 'storyblok-rich-text-react-renderer';

render(blok?.title);
```
4. Check the browser console for warnings.

### Environment
- React 18 
- Next.js 14
- Node 20 

Let me know if more details are needed

**Comment by claus** [comment]
Hey, sorry i can't reproduce that. Could you do me a favor and, if possible, send me the output of `JSON.stringify(blok?.title, null, 2)`?

**Comment by alcoceba** [comment]
Hi @claus,

For sure, this is the output for `blok.text` (I wrote `blok.title` but it's actually `blok.text`). I'm using version 3.0.10 for @storyblok/react dependency, I don't know if this could be the reason. 

```
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ",
          "type": "text"
        },
        {
          "text": "magna",
          "type": "text",
          "marks": [
            {
              "type": "bold"
            }
          ]
        },
        {
          "text": " aliqua. ",
          "type": "text"
        },
        {
          "text": "Ut enim",
          "type": "text",
          "marks": [
            {
              "type": "bold"
            }
          ]
        },
        {
          "text": " ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
          "type": "text"
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "text": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
          "type": "text"
        },
        {
          "text": "Excepteur sint occaecat cupidatat",
          "type": "text",
          "marks": [
            {
              "type": "bold"
            }
          ]
        },
        {
          "text": " non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          "type": "text"
        }
      ]
    }
  ]
}
```

With this value the warning appears. If I remove the blok, the warning isn't shown anymore.


Kind regards

**Comment by claus** [comment]
I don't get any key prop warnings with that doc.
https://codesandbox.io/p/devbox/vigorous-wright-t5h9q6

Could you maybe share a test project with me where this can be reproduced?
I do create unique keys, this must be either related to your specific setup or happen outside storyblok-rich-text-react-renderer.

**Comment by alcoceba** [comment]
Thank you for the information. The problem was on my side as I was using a custom `textResolver` while it wasn't necessary. Fixed now for me.

Thank you for your support 🙏
